name: qiskit-metal
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - addict
  - descartes
  - gdspy>=1.5.2
  - geopandas
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pint
  - pyepr-quantum>=0.8.5.5
  - pygments
  - pyside2
  - qutip
  - scipy
  - shapely
  - jupyter
  - scqubits
conda env create -n <env_name> environment.yml
conda activate <env_name>
python -m pip install --no-deps -e .
